# Generated by Django 3.1.6 on 2021-02-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tweet_id', models.PositiveIntegerField()),
                ('tweet_text', models.CharField(max_length=140)),
                ('tweet_title', models.CharField(max_length=140)),
                ('image_path', models.ImageField(blank=True, upload_to='tweet_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
