# Generated by Django 3.1.6 on 2021-02-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_tweet_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
