# Generated by Django 3.1.6 on 2021-02-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210204_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_path',
            field=models.ImageField(blank=True, default=None, upload_to='tweet_images'),
        ),
    ]
