# Generated by Django 3.1.6 on 2021-02-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210204_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_path',
            new_name='image',
        ),
    ]
